### ISSUE TITLE
janitor dependency

### ISSUE THREAD

**Issue by ajohns24** [mdogucu/bayesrules#57]
the classification_summary and other classification model eval fncns have a janitor dependency. i'm not sure how to manage that / don't want to screw up the work flow!

**Comment by mdogucu** [comment]
You can import the package. Here is an [example](https://github.com/mdogucu/bayesrules/blob/496289f6f8ce895e1659a5217eea49322f2de740/R/plot_beta_binomial.R#L12)

If you only want to import only one function rather than the whole package that is also possible with

`@importFrom package_name function_name`
